In [1]:
import numpy as np

In [3]:
# to install 
# !pip install numpy

In [5]:
a_data = np.array([[1,2],[3,4]])
print(a_data)

[[1 2]
 [3 4]]


In [ ]:
lspace_data = np.linspace(1,10,5)    # 1 to 10 divided into 5 parts
print(lspace_data)

[ 1.    3.25  5.5   7.75 10.  ]


In [7]:
zero = np.zeros((2,3))   # 2 rows and 3 columns
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
identity_matrix = np.identity(3)    # 3*3 identity matrix
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
## To convert other dimension array to 1D array
import random

eg_ar = np.array([[item for item in random.sample(range(1,100),10)], [item for item in range(10)]])
print(eg_ar)

oneD = np.ravel(eg_ar)
oneD

[[61 53 62 44 15 33 43 80 70 94]
 [ 0  1  2  3  4  5  6  7  8  9]]


array([61, 53, 62, 44, 15, 33, 43, 80, 70, 94,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9])

In [12]:
np_random = np.random.choice(np.arange(1, 100), size=10)
np_random

array([87, 38, 43, 18, 31, 22, 71, 45, 86, 17])