In [2]:
import numpy as np

In [3]:
# to install 
# !pip install numpy

In [4]:
a_data = np.array([[1,2],[3,4]])
print(a_data)

[[1 2]
 [3 4]]


In [5]:
lspace_data = np.linspace(1,10,5)    # 1 to 10 divided into 5 parts
print(lspace_data)

[ 1.    3.25  5.5   7.75 10.  ]


In [6]:
zero = np.zeros((2,3))   # 2 rows and 3 columns
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
identity_matrix = np.identity(3)    # 3*3 identity matrix
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
## To convert other dimension array to 1D array
import random

eg_ar = np.array([[item for item in random.sample(range(1,100),10)], [item for item in range(10)]])
print(eg_ar)

oneD = np.ravel(eg_ar)
oneD

[[31  2 42 74 61 48  4 59 20 72]
 [ 0  1  2  3  4  5  6  7  8  9]]


array([31,  2, 42, 74, 61, 48,  4, 59, 20, 72,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9])

In [10]:
np_random = np.random.choice(np.arange(1, 100), size=10)
np_random

array([46,  3, 24, 80, 54, 31, 59, 86, 10, 65])

### kaithgalli free code camp

In [11]:
a = np.array([1,2,3])

In [14]:
print(a.shape)
print(a.ndim)
print(a.itemsize)
print(a.size)

# equivalent
print(a.itemsize * a.size)
print(a.nbytes)

(3,)
1
8
3
24
24


In [16]:
# for better space management
print(a.dtype)

a = np.array([4,5,6], dtype=np.int16)
print(a.dtype)

int64
int16


### Accessing/ changing specific emement/row/column

In [18]:
# [row, column]
# [start, end, step]

n = np.array([[item for item in random.sample(range(1,100),10)], [item for item in range(10)]])
print(n)

[[40 23 12 10 38 27  5 98 86 97]
 [ 0  1  2  3  4  5  6  7  8  9]]


In [21]:
print(n[0,5])

# whole row
print(n[:, 1])

# whole column
print(n[0, :])

27
[23  1]
[40 23 12 10 38 27  5 98 86 97]


In [22]:
print(n[1,::2])  # all element from second row step size is 2

[0 2 4 6 8]


In [28]:
# to change items identity
a = np.identity(3)
print(a, '\n after change')

a[:1, 1] = 12
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
 after change
[[ 1. 12.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [31]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [33]:
b[1,1,0]

np.int64(7)

In [34]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [35]:
b[:,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing different types of array

In [41]:
# all 0s matrix
# np.zeros(2,3)   # gives error
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [43]:
np.ones((2,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [44]:
np.full((2,3), 9)

array([[9, 9, 9],
       [9, 9, 9]])

In [47]:
l_array = np.zeros((2,3))
print(l_array)

np.full_like(l_array, 7)

[[0. 0. 0.]
 [0. 0. 0.]]


array([[7., 7., 7.],
       [7., 7., 7.]])

In [50]:
np.random.random_sample(l_array.shape)      

array([[0.59835   , 0.10560874, 0.83500734],
       [0.97684977, 0.27240142, 0.32333218]])

In [53]:
np.random.rand(3,2)             # no need to pass as ((3,2))

array([[0.49785178, 0.44481211],
       [0.33939652, 0.91551089],
       [0.50547932, 0.72880842]])

In [59]:
# random integer value
print(np.random.randint(7))

print(np.random.randint(3, size=(2,2)))
np.random.randint(7, 17, size=(3,3))

6
[[2 0]
 [2 0]]


array([[ 9, 12, 15],
       [13,  7, 12],
       [16,  9, 11]], dtype=int32)

In [60]:
# identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [69]:
# repeat an array
arr = np.array([1,2,3])
r1 = np.repeat(arr,3, axis=0)
print(r1)

arr2 = np.array([[1,2,3]])
r2 = np.repeat(arr2,3, axis=0)
print(r2)

r3 = np.repeat(arr2, 3, axis=1)
print(r3)

[1 1 1 2 2 2 3 3 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


In [75]:
eg = np.zeros((5,5))
eg[0,:] = 1
eg[4,:] = 1
eg[:,0] = 1
eg[:,4] = 1
eg[2,2] = 9
print(eg)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [79]:
op = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9
op[1:-1, 1:-1] = z
print(op)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### BEcareful while copying arrays

In [81]:
a = np.array([1,2,3])
b = a 
b[0] = 99
print(b)
# points to same(a and b)
print(a)

[99  2  3]
[99  2  3]


In [83]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 99
print(b)
# points to same(a and b)
print(a)

[99  2  3]
[1 2 3]


### Mathematics

In [89]:
a = np.array([1,2,3,4])
print(a, '\n')
print(a+2, '\n')
print(a-2, '\n')
print(a*2, '\n')
print(a/2, '\n')


[1 2 3 4] 

[3 4 5 6] 

[-1  0  1  2] 

[2 4 6 8] 

[0.5 1.  1.5 2. ] 



In [90]:
b = np.array([1,0,0,1])
print(a+b)

[2 2 3 5]


In [91]:
a ** 2

array([ 1,  4,  9, 16])

In [96]:
print(np.sin(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


### linear Algebra

In [98]:
a = np.ones((2,3))
print(a)
b = np.full((3,2), 2)
print(b)

# resulting matrix shape is (m*n) * (n*q) = m,q    
# The no of column in first matrix should be equal to no of rows in second matrix
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [100]:
# to find determinant
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

In [102]:
# docs.scipy.org/doc/numpy/reference for further learning

### Statistics

In [108]:
stats_arr = np.array([[1,2,3],[3,4,5]])
print(stats_arr, '\n')
print(np.min(stats_arr))
print(np.max(stats_arr, axis=1))
print(np.max(stats_arr))
print(np.sum(stats_arr))

[[1 2 3]
 [3 4 5]] 

1
[3 5]
5
18


### Reorganizing Arrays

In [112]:
before = np.array([[1,2,3,4],[4,5,6,7]])
print(before, '\n')

after = before.reshape(4,2)
print(after)

[[1 2 3 4]
 [4 5 6 7]] 

[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [114]:
np.vstack([before, before])

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [1, 2, 3, 4],
       [4, 5, 6, 7]])

In [115]:
np.hstack([before, before])

array([[1, 2, 3, 4, 1, 2, 3, 4],
       [4, 5, 6, 7, 4, 5, 6, 7]])

In [ ]:
np.hsplit(before,2)
# np.hsplit(before, 3)        # gives error because not divisible

[array([[1, 2],
        [4, 5]]),
 array([[3, 4],
        [6, 7]])]

In [121]:
np.vsplit(after,2)

[array([[1, 2],
        [3, 4]]),
 array([[4, 5],
        [6, 7]])]

### Miscellaneous
#### load data from file

In [126]:
file_data = np.genfromtxt('numpy_load.txt', delimiter=',')
print(file_data)

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
  19. 20.]
 [ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32. 34. 36.
  38. 40.]
 [ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21. 23. 25. 27. 29. 31. 33. 35.
  37. 39.]]


#### Boolean Masking and Advanced Indexing

In [134]:
arr_index = file_data[file_data>20]
print(arr_index)

[22. 24. 26. 28. 30. 32. 34. 36. 38. 40. 21. 23. 25. 27. 29. 31. 33. 35.
 37. 39.]


In [130]:
arr_index[[5,7,9]]

array([32., 36., 40.])

In [142]:
file_data

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20.],
       [ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24., 26.,
        28., 30., 32., 34., 36., 38., 40.],
       [ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23., 25.,
        27., 29., 31., 33., 35., 37., 39.]])

In [136]:
np.any(file_data > 25, axis=0)

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True])

In [138]:
np.all(file_data > 30, axis=0)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [139]:
np.all(file_data > 30, axis=1)

array([False, False, False])

In [141]:
((file_data > 20) & (file_data < 30))

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False,  True,  True,  True,  True, False, False, False, False,
        False, False],
       [False, False, False, False, False, False, False, False, False,
        False,  True,  True,  True,  True,  True, False, False, False,
        False, False]])

##### axis = 0 is columns based and axis = 1 is row based

In [157]:
a = np.ones((6,5))
a[:, 0] = [1,6,11,16,21,26]
a[:, 1] = a[:, 0] + 1
a[:, 2] = a[:, 1] + 1
a[:, 3] = a[:, 2] + 1
a[:, 4] = a[:, 3] + 1
a

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.],
       [26., 27., 28., 29., 30.]])

In [164]:
# index for 11,12,16,17
print(a[2:4, 0:2],'\n')

# index for 2,8,14,20
print(a[[0,1,2,3],[1,2,3,4]], '\n')

# index for 4,5 24,25,29,30
a[[0,4,5],3:]

[[11. 12.]
 [16. 17.]] 

[ 2.  8. 14. 20.] 



array([[ 4.,  5.],
       [24., 25.],
       [29., 30.]])

## Vectorization in Numpy

OK! So loops can slow your code. So what to do now? most of the functions you call using NumPy in your python code are merely wrappers for underlying code in C where most of the heavy lifting happens. In this way, NumPy can move the execution of loops to C, which is much more efficient than Python when it comes to looping.

Notice this can be only done as the array enforces the elements of the array to be of the same kind. 

#### dot product, outer product, element wise product, sum of numbers

In [166]:
# dot product
# The dot product is an algebraic operation in which two vectors of equal length are multiplied together

a = np.array([2,4,6])
b = np.array([1,3,5])
np.dot(a,b)


# When two matrices, a, and b, of the same length are used, the dot product is calculated by taking the transpose of the first matrix, a’, 
# and then performing matrix multiplication with the second matrix, b.

np.int64(44)

In [174]:
# outer product
# When considering two vectors, a and b, with dimensions n x 1 and m x 1, respectively, the outer 
# product will result in a rectangular matrix of size n x m.
print(np.outer(a,b))
p = a.reshape(3,1)
q = b.reshape(3,1)
print(p, '\n -----\n', q)
np.outer(p, q)

[[ 2  6 10]
 [ 4 12 20]
 [ 6 18 30]]
[[2]
 [4]
 [6]] 
 -----
 [[1]
 [3]
 [5]]


array([[ 2,  6, 10],
       [ 4, 12, 20],
       [ 6, 18, 30]])

In [ ]:
# element wise product

# Each element of the first matrix is multiplied by its corresponding element 
# in the second matrix in the algebraic operation known as element-wise 
# multiplication of two matrices. The matrices’ dimensions should match.

np.multiply(a, b)

array([ 2, 12, 30])

In [176]:
# sum of numbers
np.sum(np.arange(100))

np.int64(4950)

### Broadcasting in Numpy

Broadcasting in NumPy refers to the ability of performing operations on arrays with 
different shapes by automatically expanding the smaller array's shape to match the larger array's shape.

In [177]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])     
array2 = np.array([10, 20, 30]) 
print(array1 + array2)

[[11 22 33]
 [14 25 36]]


In [178]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  
print(a + b)

[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [179]:
# eg 
# [[0,0,0,],[10,10,10],[20,20,20],[30,30,30]] i.e a(4*3) 
# [0,1,2] i.e b(1,3)

# if we need to add these the b(1,3) will stretch to be (4,3) by [[0,1,2],[0,1,2],[0,1,2],[0,1,2]]

# now output will be generated as [[0,1,2], [10,11,12], [20,21,22], [30,31,32]]